# Site settings
name: ControlC.fm
my_name: Control C
title: Control C
email: feedback@controlc.fm
description: "A podcast where Chris Becker and Jeff Uthaichai talk about tech, beer and more"
baseurl: ""
url: "http://www.controlc.fm"

# Image paths
blog_image_url: "/images/episodes/"
main_avatar: "/images/jeff_and_chris.png"
podcast_cover: "/images/podcast_cover.png"

# Build settings
markdown: kramdown
permalink: /episode/:year/:month/:day/:title/
source: src
